name: Automate Wazuh Alerts Processing

on:
  schedule:
    - cron: '0 18 * * *' # Runs every day at 6 PM UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        echo "${{ secrets.DO_SSH_KEY }}" > private_key
        chmod 600 private_key

    - name: Run commands on DigitalOcean Droplet
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.DO_SSH_KEY }}
        script: |
          rm -f /tmp/fetch_alerts.sh /tmp/analyze_alerts.py /tmp/alerts.json /tmp/summary.json
          curl -o /tmp/fetch_alerts.sh https://raw.githubusercontent.com/jorgesoft/honeylab/main/fetch_alerts.sh
          curl -o /tmp/analyze_alerts.py https://raw.githubusercontent.com/jorgesoft/honeylab/main/analyze_alerts.py
          chmod +x /tmp/fetch_alerts.sh
          bash /tmp/fetch_alerts.sh ${{ secrets.WAZUH_USER }} ${{ secrets.WAZUH_PASSWORD }}
          python3 /tmp/analyze_alerts.py /tmp/alerts.json /tmp/summary.json

    - name: Upload summary.json to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        scp -i private_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/summary.json ./summary.json
        aws s3 cp ./summary.json s3://baitfluentd/summary.json --region us-east-1
